### ISSUE TITLE
fail to exec 'yt-fts search "existing in large metropolaten center" --export'

### ISSUE THREAD

**Issue by bk111** [NotJoeMartinez/yt-fts#129]
>yt-fts search "existing in large metropolaten center" --export
- Try shortening the search to specific words
- Try using the wildcard operator * to search for partial words
- Try using the OR operator to search for multiple words
    - EX: "existing OR in OR large OR metropolaten OR center"

**Comment by bk111** [comment]
yt-fts search "are you a teacher"
- Try shortening the search to specific words
- Try using the wildcard operator * to search for partial words
- Try using the OR operator to search for multiple words
    - EX: "are OR you OR a OR teacher"

**Comment by NotJoeMartinez** [comment]
Can you elaborate? It looks like you're seeing the error message triggered when the full text search returns no results.
