### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by kacperlukawski** [NotJoeMartinez/yt-fts#15]
Hi, what is the license of that code? The LICENCE file is missing.

**Comment by TeddyBear06** [comment]
[The Unlicense](https://unlicense.org/) used by [yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/LICENSE) or [ytdl-org](https://github.com/ytdl-org/youtube-dl/blob/master/LICENSE) (and many others)?

**Comment by NotJoeMartinez** [comment]
Added license in b6738c0
