### ISSUE TITLE
table Videos has no column

### ISSUE THREAD

**Issue by sharpsteelsoftware** [NotJoeMartinez/yt-fts#160]
I get this when I try to yt-fts update or download. Is it because I was on an older version? Is there a way to wipe my entire SQLite database?

**Comment by NotJoeMartinez** [comment]
@sharpsteelsoftware Yes we added breaking changes to the schema in v0.1.49 https://github.com/NotJoeMartinez/yt-fts/pull/144. The SQLite database is stored in `~/.config/yt-fts/subtitles.db` and deleting it will "reset" the database the next time you run `yt-fts`. If you're on windows run `yt-fts config` to see where the database is stored. I recommend deleting the whole directory  `rm -rf ~/.config/yt-fts` but be warned that this will also delete any embeddings you have stored `~/.config/yt-fts/chroma` but if you intend to reset the db I'm assuming you don't want those either.
