### ISSUE TITLE
[Feature request] Playlist support

### ISSUE THREAD

**Issue by quidnu** [NotJoeMartinez/yt-fts#18]
Please add playlist support. Many video collections of interest are organized in playlists and not channels. I don't know if the identifier for playlists is in a different namespace. yt-dlp support playlists.

**Comment by NotJoeMartinez** [comment]
This is something I want to add but presents a design problem. Every video in the playlist needs to be connected to a channel, and If one of the videos in a playlist is already saved in the database it will

**Comment by NotJoeMartinez** [comment]
Added in #139, available on [v0.1.44 ](https://github.com/NotJoeMartinez/yt-fts/releases/tag/v0.1.44)
