### ISSUE TITLE
Integrate semantic search with OpenAI embedings API

### ISSUE THREAD

**Issue by umaar** [NotJoeMartinez/yt-fts#21]
Is the search a traditional exact text match? If so, having semantic searching via embeddings/completion would be great!

**Comment by NotJoeMartinez** [comment]
The [current implementation](https://github.com/NotJoeMartinez/yt-fts/blob/966475569832ea1f41c5b75680c9e0b6ec1c0840/yt_fts/db_scripts.py#L81) uses the SQLite LIKE keyword, meaning an exact match isn't necessary, but it is still somewhat limited. I plan to implement true full-text search with [sqlite-utils](https://sqlite-utils.datasette.io/en/stable/python-api.html#full-text-search), which should enhance query speed and introduce more flexibility for features like relevancy ranking.

Several users brought up the idea of semantic search on the [HN thread](https://news.ycombinator.com/item?id=36010288), and it's an area I'm interested in exploring. I don't have much experience with vector search databases, but my rough plan is the following:

- Using the OpenAI Python library to authenticate users with their API key.
- Adding a command to generate embeddings from one of their [models](https://platform.openai.com/docs/guides/embeddings/embedding-models).
- Somehow creating a searchable vector database with the embeddings data, possibly using the [openai-to-sqlite](https://github.com/simonw/openai-to-sqlite) library.

As I mentioned, I'm not very familiar with this area, so any suggestions are highly appreciated. Thank you!

**Comment by umaar** [comment]
Sounds excellent, thank you for htis!

**Comment by NotJoeMartinez** [comment]
@umaar Added experimental integration with semantic search via OpenAI embeddings on #48  

- https://github.com/NotJoeMartinez/yt-fts#Semantic-Search-via-OpenAI-embeddings-API
