### ISSUE TITLE
Prevent duplicate subtitle entries in db

### ISSUE THREAD

**Issue by NotJoeMartinez** [NotJoeMartinez/yt-fts#23]
The current way we parse vtt files inserts duplicate quote entries with time stamp off by a couple seconds. This is because the vtt files we get from `yt-dlp` contain duplicate entries except one of them has a bunch of markup to segment the quote. See [line 192](https://github.com/NotJoeMartinez/yt-fts/blob/b7a32ea78ab869dc11422fd70a7a9c314384cf79/yt_fts/yt_fts.py#L192). Removing these duplicates would probably speed something up

**Comment by chapmanjacobd** [comment]
I wonder if the ttml format has fewer duplicates. I read that here: https://old.reddit.com/r/youtubedl/comments/yckryy/getting_a_clean_subtitle_form_auto_generated/

**Comment by NotJoeMartinez** [comment]
Fixed with #27
