### ISSUE TITLE
Wrong channel downloaded

### ISSUE THREAD

**Issue by lightonflux** [NotJoeMartinez/yt-fts#46]
Used link: https://youtube.com/@TomScottGo
yt_fts version: 0.1.15

Downloaded subs where from all from @tomscottplus. This is not what i expected.

**Comment by TeddyBear06** [comment]
Hi,

Do you mean you used this link [https://www.youtube.com/@TomScottGo/videos](https://www.youtube.com/@TomScottGo/videos) like the command below?

```
yt-fts download "https://www.youtube.com/@TomScottGo/videos"
```

If I'm not mistaken, the channel ID is extracted from this specific URL (the /videos at the end of the URL is required).

**Comment by NotJoeMartinez** [comment]
Seems like this happens on channels where they have extra channels listed on their home page. 

problem might be from [line 38](https://github.com/NotJoeMartinez/yt-fts/blob/040eb56453b60e09323253e4e54bd9447f7feeb9/yt_fts/download_utils.py#L38) in this function because it gets the first channel id it finds:
```python
def get_channel_id(url, s):
    """
    Scrapes channel id from the channel page
    """
    res = s.get(url)
    if res.status_code == 200:
        html = res.text
        channel_id = re.search('channelId":"(.{24})"', html).group(1)
        return channel_id
    else:
        return None
```

**Comment by TeddyBear06** [comment]
You're right. 

There are multiple `channelId` matches (exactly 4) on the homepage (but only one the channel's videos page, as expected).

We need to check the given channel URL against the expected pattern.

**Comment by lightonflux** [comment]
Thanks for adding the code in #52. That would have been good enough. Because i aborted a task, as i "couldn't" download scotts subtitles before. :+1:
