### ISSUE TITLE
README: How to use old subtitles db?

### ISSUE THREAD

**Issue by lightonflux** [NotJoeMartinez/yt-fts#61]
The program downloaded many subtitles. It took some time. But then i closed the terminal session. And now it does not appear to recognise the .db file in the current working path. Is there a way to specify the db file to use?

**Comment by NotJoeMartinez** [comment]
### Possibility 1: you changed directories 
The tool currently makes a database in the current working directory you run the tool. So if you download subtitles then open a new terminal in another directory it won't know where this previous database was. to fix this simply go back into the original directory and run `yt-fts list` and it should show your original db. 

if you don't know where you originally ran the command you can try: 
```bash 
find ~ -type f -iname "subtitles.db"
```

**important**: when ever you run any command like `list` in a new directory it will create an empty database if no `subtitles` database is found 

A fix to prevent this confusion has been proposed: "Save database and config files to user .config folder #26" 

### Possibility 2: session closed before db processing 
If you closed the session before it showed this "adding to database" loading screen then they were unfortunately deleted before they cold be saved to the database.

<img width="578" alt="image" src="https://github.com/NotJoeMartinez/yt-fts/assets/39905973/b197aba5-c77d-4a2f-b50f-cb11a2f7ad67">
 
### Possibility 3: version conflicts
What version are you running? check with `yt-fts --version` if you had a database saved before `0.1.16` the updated, the older databases might not be compatible.

**Comment by lightonflux** [comment]
I think it is possibility 2:

![Bildschirmfoto vom 2023-06-10 22-17-27](https://github.com/NotJoeMartinez/yt-fts/assets/1377943/3ea57dad-59d7-4213-b329-3c2243ac5616)
![Bildschirmfoto vom 2023-06-10 22-17-19](https://github.com/NotJoeMartinez/yt-fts/assets/1377943/9adaf0da-e644-4374-9fb1-7c08c61b2552)
![Bildschirmfoto vom 2023-06-10 22-17-10](https://github.com/NotJoeMartinez/yt-fts/assets/1377943/cb2120b9-f3f4-45f8-acab-7020aa1672a3)
![Bildschirmfoto vom 2023-06-10 22-16-58](https://github.com/NotJoeMartinez/yt-fts/assets/1377943/b62deac3-71d5-4682-8315-0d6a367f625f)


How would one check possibility 3?

**Comment by NotJoeMartinez** [comment]
I've settled on what I believe to be a "stable" schema for this project so hopefully, we'll avoid breaking existing 
databases every update. 
```sql
CREATE TABLE [Channels] (
   [channel_id] TEXT PRIMARY KEY,
   [channel_name] TEXT NOT NULL,
   [channel_url] TEXT NOT NULL
);
CREATE TABLE [Videos] (
   [video_id] TEXT PRIMARY KEY,
   [video_title] TEXT NOT NULL,
   [video_url] TEXT NOT NULL,
   [channel_id] TEXT REFERENCES [Channels]([channel_id])
);
CREATE TABLE [Subtitles] (
   [subtitle_id] INTEGER PRIMARY KEY,
   [video_id] TEXT REFERENCES [Videos]([video_id]),
   [start_time] TEXT NOT NULL,
   [stop_time] TEXT,
   [text] TEXT NOT NULL
);
CREATE VIRTUAL TABLE [Subtitles_fts] USING FTS5 (
    [text],
    content=[Subtitles]
)
CREATE TABLE [SemanticSearchEnabled] (
   [channel_id] TEXT REFERENCES [Channels]([channel_id])
);
```
