### ISSUE TITLE
Support Live Streamed Videos

### ISSUE THREAD

**Issue by abe-101** [NotJoeMartinez/yt-fts#79]
It seems that the download command only downloads transcripts of the **uploaded** videos
It would be nice to also support videos which are live streamed

**Comment by jasontucker** [comment]
I agree, it only supports the uploaded videos and doesnt support the live streamed ones. Any thoughts about adding this functionality?

**Comment by NotJoeMartinez** [comment]
@abe-101 do you have any examples of channels where you experience this issue? I could be an issue with the auto generated subtitles not loading until a period of time after they first streamed.

**Comment by NotJoeMartinez** [comment]
So we can get all live streamed urls from a channel with:
```bash
yt-dlp --flat-playlist --print id "https://www.youtube.com/@channel_name/streams"
```
This is implemented with `get_videos_list` function
```python
def get_videos_list(channel_url):
    """
    Scrapes list of all video urls from the channel
    """
    console = Console()

    with console.status("[bold green]Scraping video urls, this might take a little...") as status:
        cmd = [
            "yt-dlp",
            "--flat-playlist",
            "--print",
            "id",
            f"{channel_url}"
        ]
        res = subprocess.run(cmd, capture_output=True, check=True)
        list_of_videos_urls = res.stdout.decode().splitlines()

    return list_of_videos_urls 
```
This will work the same with `channel_url + "/streams"` so the solution is to somehow extend this functions
return values with the results from a search using the `/streams` path.

**Comment by NotJoeMartinez** [comment]
Added in "Support Live Streamed Videos #112"

**Comment by abe-101** [comment]
seeing this now

do you still need help testing out live streams?

**Comment by NotJoeMartinez** [comment]
If you see any other issues pop up feel free to make another issue, thanks
